<?php
/* Originally from Icinga Web 2 Elasticsearch Module (c) 2017 Icinga Development Team | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */
/* icingaweb2-module-teamdashboards (c) 2023 | GPLv2+ */

namespace Icinga\Module\Teamdashboards\Forms;

use Icinga\Data\Filter\Filter;
use Icinga\Forms\RepositoryForm;
use Icinga\Module\Teamdashboards\MappingIniRepository;

/**
 * Create, update and delete a Config
 */
class MappingForm extends RepositoryForm
{

    public function init()
    {
        $this->repository = new MappingIniRepository();
        $this->redirectUrl = 'teamdashboards/mapping';

    }


    /**
     * Set the identifier
     *
     * @param   string  $identifier
     *
     * @return  $this
     */
    public function setIdentifier($identifier)
    {
        $this->identifier = $identifier;

        return $this;
    }

    /**
     * Set the mode of the form
     *
     * @param   int $mode
     *
     * @return  $this
     */
    public function setMode($mode)
    {
        $this->mode = $mode;

        return $this;
    }

    protected function onUpdateSuccess()
    {
        if ($this->getElement('btn_remove')->isChecked()) {
            $this->setRedirectUrl("teamdashboards/mapping/delete?id={$this->getIdentifier()}");
            $success = true;
        } else {
            $success = parent::onUpdateSuccess();
        }

        return $success;
    }

    protected function createBaseElements(array $formData)
    {
        $this->addElement(
            'text',
            'name',
            array(
                'description'   => $this->translate('Name of the user to fetch the dashboard from'),
                'label'         => $this->translate('Dashboard Username'),
                'placeholder'   => 'username',
                'required'      => true
            )
        );

        $this->addElement(
            'text',
            'alias',
            array(
                'description'   => $this->translate('Define an Alias that will be shown instead of the username as the menueitem'),
                'label'         => $this->translate('Dashboard Alias'),
                'placeholder'   => 'Dashboard XY',
            )
        );

        $this->addElement(
            'number',
            'priority',
            array(
                'description'   => $this->translate('Priority of the Dashboard'),
                'label'         => $this->translate('Priority'),
                'required'      => true
            )
        );

        $this->addElement(
            'checkbox',
            'enabled',
            array(
                'description'       => $this->translate('Enable or disable this entry'),
                'label'             => $this->translate('Enabled'),
                'value'=>1
            )
        );

    }

    protected function createInsertElements(array $formData)
    {
        $this->createBaseElements($formData);

        $this->setTitle($this->translate('Create a New Mapping'));

        $this->setSubmitLabel($this->translate('Save'));
    }

    protected function createUpdateElements(array $formData)
    {
        $this->createBaseElements($formData);

        $this->setTitle(sprintf($this->translate('Update Mapping %s'), $this->getIdentifier()));

        $this->addElement(
            'submit',
            'btn_submit',
            [
                'decorators'            => ['ViewHelper'],
                'ignore'                => true,
                'label'                 => $this->translate('Save')
            ]
        );

        $this->addElement(
            'submit',
            'btn_remove',
            [
                'decorators'            => ['ViewHelper'],
                'ignore'                => true,
                'label'                 => $this->translate('Remove')
            ]
        );

        $this->addDisplayGroup(
            ['btn_submit', 'btn_remove'],
            'form-controls',
            [
                'decorators' => [
                    'FormElements',
                    ['HtmlTag', ['tag' => 'div', 'class' => 'control-group form-controls']]
                ]
            ]
        );
    }

    protected function createDeleteElements(array $formData)
    {
        $this->setTitle(sprintf($this->translate('Remove Mapping %s'), $this->getIdentifier()));

        $this->setSubmitLabel($this->translate('Yes'));
    }

    protected function createFilter()
    {
        return Filter::where('name', $this->getIdentifier());
    }

    protected function getInsertMessage($success)
    {
        return $success
            ? $this->translate('Mapping created')
            : $this->translate('Failed to create Mapping');
    }

    protected function getUpdateMessage($success)
    {
        return $success
            ? $this->translate('Mapping updated')
            : $this->translate('Failed to update Mapping');
    }

    protected function getDeleteMessage($success)
    {
        return $success
            ? $this->translate('Mapping removed')
            : $this->translate('Failed to remove Mapping');
    }
}
